project:
  type: website
  preview:
    port: 7777
  # output-dir: docs

website:
  title: "Kara Combs"
  description: "Personal website of Kara Combs"
  site-url: ""
  favicon: assets/Combs_Digital_Portrait_Square.png
  navbar:
    left:
      - text: Home
        href: /
      - text: Education & Experience
        href: education_experience.qmd
      - text: Publications
        href: publications.qmd
      - text: Awards
        href: awards.qmd
      - text: Service
        href: service.qmd
      - text: Mentees
        href: mentees.qmd
      - text: Features
        href: features.qmd
    right:
      - icon: github
        href: https://github.com/karacombs
      - icon: linkedin
        href: https://www.linkedin.com/in/karacombs33
      - icon: envelope
        href: mailto:kara.combs.1@us.af.mil
  page-footer:
    left: "Â© 2025 Kara Combs"
    right: |
      Built with [Quarto](https://quarto.org).

format:
  html:
    theme:
      - pulse
    toc: true
    toc-depth: 3
    number-sections: false
    css: styles.css
    code-copy: true
    smooth-scroll: true
execute:
  freeze: auto

jupyter: python3
python:
  executable: .venv/Scripts/python.exe
  packages:
    - pandas
    - plotly
    - jupyter
    - pyyaml
    - ipykernel